eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:  
      enabled: true
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
