from: git-test-1.0
spring:
  cloud:
    bus:
      trace:
        enabled: true
  sleuth:
    sampler:
      percentage: 0.5
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: springcloud
    password: banggood
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false