spring: 
  sleuth:
    sampler:
      percentage: 0.5
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true