spring:
    sleuth:
      log:
        json:
          enabled: true
      sampler:
        percentage: 0.5
  datasource:
      url: jdbc:mysql://192.168.99.100:3306/study
      username: root
      password: banggood
      driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://192.168.99.100:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false